<a href="https://colab.research.google.com/github/maheshwarihit/Pytorch_Starch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSOR MATH OPERATIONS**



*   Add Subtract Mutliply Divide Remainder Exponents
*   Shorthand and longhand
*   Reassignment





In [3]:
import torch
import numpy as np

In [4]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [5]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [14]:
#add longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [11]:
#sub funtion
torch.sub(tensor_b , tensor_a)

tensor([4, 4, 4, 4])

In [12]:
#Multiply
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [13]:
#Mul fun.
torch.mul(tensor_a , tensor_b)

tensor([ 5, 12, 21, 32])

In [15]:
#Divison
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [16]:
#Div longhand
torch.div(tensor_b , tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
#Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [18]:
#remainder longhand
torch.remainder(tensor_b ,tensor_a)

tensor([0, 0, 1, 0])

In [19]:
#exponents / power
torch.pow(tensor_a , tensor_b)

tensor([    1,    64,  2187, 65536])

In [20]:
#Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [21]:
#Reassignment
tensor_a +tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a = tensor_a + tensor_b