<a href="https://colab.research.google.com/github/maheshwarihit/Pytorch_Starch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSORS

# **TENSORS**



*  A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
*  Similar To Numpy Arrays,but full of fun things that make them work better on GPU's (vs regular CPU's)
*  More suitable for deep learning than a numpy array.







In [ ]:
import torch
import numpy as np

#**LISTS**


In [ ]:
#one-dimensional array
list=[1,2,3,4]
list


[1, 2, 3, 4]

In [ ]:

#multi-dimensional array
list2=[[1,2,3,4,5],[6,7,8,9,0]]
list2

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

# **NUMPY ARRAYS**

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.83664332, 0.8624942 , 0.0037011 , 0.29028479],
       [0.9840337 , 0.01805237, 0.56441155, 0.84131389],
       [0.30816677, 0.35592715, 0.79684852, 0.75099304]])

In [ ]:
np1.dtype

dtype('float64')

# **TENSORS**

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.9209,  0.5036, -0.1005, -1.2696],
        [ 0.1916, -0.5771, -1.5601,  1.8971],
        [ 0.0202, -0.2585, -0.5261, -2.0357]])

In [ ]:
tensor_3d = torch.zeros(2,3,3)
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
#create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8366, 0.8625, 0.0037, 0.2903],
        [0.9840, 0.0181, 0.5644, 0.8413],
        [0.3082, 0.3559, 0.7968, 0.7510]], dtype=torch.float64)